INSERT INTO PESSOAL (NOME, CARGO, FORMACAO_ID) VALUES (?, ?, ?)
SELECT * FROM PESSOAL WHERE ID_PESSOAL = ?
UPDATE PESSOAL SET NOME = ?, CARGO = ?, FORMACAO_ID = ? WHERE ID_PESSOAL = ?
DELETE FROM PESSOAL WHERE ID_PESSOAL = ?
SELECT * FROM PESSOAL
